In [60]:
# Assignment
# ====
# 1. print out python from the record below
record = {'k1':[{'nest_key':['this is deep',['python']]}]}
record["k1"][0]["nest_key"][1][0]

# 2. Print out blacktech from the info below
info = {'k1':[1,2,{'k2':['this is tricky',{'tough':[1,2,['blacktech']]}]}]}
info['k1'][2]['k2'][1]['tough'][2][0]

# 3. Write a program that prints the integers from 1 to 100. 
# But for multiples of three print "Fizz" instead of the number, 
# and the multiples of five print "Buzz". 
# For numbers which are multiples of both three and five print "FizzBuzz".

# for i in range(1,101):
#     if i % 3 ==0 and i % 5 == 0:
#         print("FizzBuzz")
#     elif i % 3 == 0:
#         print("Fizz")
#     elif i % 5 == 0:
#         print("Buzz")
#     else:
#         print(i)


# 4. create a program that stores value. Users are expected to guess the number.
# if the user guesses correctly, return "You win", else, return "try again"
# hint: you can get info from the user using the input() method
# eg. first_name = input("enter your name")

# import random
# number = random.randint(1,11)
# guess = input("Guess a number between 1 and 10")
# if guess == number:
#     print("You win")
# else:
#     print("Try again")

# 5. create a program that finds the largest of 3 numbers entered by the user

# num1 = int(input("Enter first number"))
# num2 = int(input("Enter second number"))
# num3 = int(input("Enter third number"))

# if num1 > num2 and num1 > num3:
#     print(num1,"is the largest")
# elif num2 > num1 and num2 > num3:
#     print(num2, "is the largest")
# elif num3 > num1 and num3 > num2:
#     print(num3,"is the largest")
# else:
#     print("No largest number")

# 6. Create a program that accepts 2 numbers and an operator eg. 5 6, + 
# then perform an operation based on what the user enters eg 5 + 6 if the user enters 2, 8, * 
# it should return 2 * 8 and show the answer

# num1 = int(input("Enter first number"))
# sign = input("Enter an operator eg. +, -, /, *")
# num2 = int(input("Enter second number"))

# if sign == "+":
#     print(num1 + num2)
# elif sign == "-":
#     print(num1 - num2)
# elif sign == "*":
#     print(num1 * num2)
# elif sign == "/":
#     print(num1 / num2)
# else:
#     print("Invalid operator")

# 7. create a program that takes a score and shows the grade based on the score
# eg.
# 90 - 100 ("Grade A")
# 70 - 89  ("Grade B")
# 50 - 69 ("Grade C")
# 30 - 49 ("Grade D")
# 0 - 29  ("Grade F")

# score = float(input("Enter score"))
# if score >= 90 and score <= 100:
#     print("Grade A")
# elif score >= 70 and score <= 89:
#     print("Grade B")
# elif score >= 50 and score <= 69:
#     print("Grade C")
# elif score >= 30 and score <= 49:
#     print("Grade D")
# elif score >= 0 and score <= 29:
#     print("Grade F")
# else:
#     print("Invalid score")

# 8.  
# record = "this is the time to attend python training"
# # bring out the words that start from 't'

# for i in record.split():
#     if i.startswith("t"):
#         print(i)

# 9. 
# words = "I am here"

# words = words.split()
# words.reverse()
# " ".join(words)

# print out the word in reverse to read "here am I"
# words = "I am here"
# words = words.split()
# words[::-1]
# " ".join(words)

# 10. 
# info = [1,1,1,1,2,2,3,3,3,3,4,5]
# # bring out unique values from the code above without using the set() function.

# basket = []
# for i in info:
#     if i not in basket:
#         basket.append(i)
# print(basket)

# bonus.           
words = 'Python is not hard. You agree with me right?'

for i in words.split():
    if len(i) % 2 == 0:
        print(i)
        
# Print every word in this sentence above that has an even number of letters

Python
is
with
me
right?


In [62]:
#Numpy - is a linear algebra library for python. It can be used to generate data.
# numpy also works with multi dimensional array
import numpy as np

In [63]:
mylist = [1,2,3,4,5]
type(mylist)

list

In [65]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4, 5])

In [66]:
type(x)

numpy.ndarray

In [67]:
#numpy array are faster than python list

data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [69]:
record = np.array(data)
record

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# generating data with numpy
# arange() - generates a range of positive numbers
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [78]:
# generating evenly spaced numbers

np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [88]:
# generating random numbers
# rand generates floating random numbers greater than 0 and less than 1
np.random.rand(5,4)

array([[0.36110501, 0.23762555, 0.85090248, 0.35476605],
       [0.10582938, 0.86651927, 0.63226511, 0.60721392],
       [0.42001946, 0.40430773, 0.38876514, 0.09769373],
       [0.86265194, 0.19626757, 0.95600649, 0.94099187],
       [0.05786663, 0.17527828, 0.97059697, 0.0937249 ]])

In [93]:
# randn will genrate random numbers that can be less than 0 and greater than 1
np.random.randn(10,3)

array([[-0.45209058,  0.88356583, -0.39213807],
       [-0.93800247,  0.11401886, -1.02408979],
       [ 0.31046624, -0.21999233,  0.6205497 ],
       [ 0.10101941, -1.0118971 , -0.50606542],
       [ 0.56575693,  1.65122859,  0.84205334],
       [ 1.4807253 ,  1.62158555, -1.49869314],
       [ 1.78773433,  1.88022217,  0.21610104],
       [-2.12504629, -0.39015567, -0.30955616],
       [-0.02198143, -0.26730639, -0.71574937],
       [ 1.74975125,  0.72295741,  0.2272694 ]])

In [99]:
np.random.randint(1,4,24).reshape(6,4)

array([[3, 3, 3, 1],
       [3, 1, 1, 3],
       [1, 2, 1, 3],
       [1, 2, 2, 2],
       [1, 2, 1, 2],
       [1, 3, 2, 2]])

In [101]:
# indexing numpy array

x = np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [116]:
x[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [106]:
x[1][2]

8

In [107]:
x[3][0]

16

In [108]:
# slicing
x[4][:3]

array([21, 22, 23])

In [113]:
# slicing numpy array
x[4][3:]

array([24, 25])

In [117]:
x[1:3,0:2]

array([[ 6,  7],
       [11, 12]])

In [119]:
# arithetic with pythion list
mylist + mylist

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [120]:
np.array(mylist) + np.array(mylist)

array([ 2,  4,  6,  8, 10])

In [121]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [122]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [124]:
#broadcasting
np.arange(1,10).reshape(3,3) + np.arange(1,4)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [126]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
np.arange(1,4)

array([1, 2, 3])

In [ ]:
[1, 2, 3]
[1, 2, 3]
[1, 2, 3]

In [131]:
#it must be same dimention either row wise or column wise
np.arange(1,10).reshape(3,3) + np.arange(1,3)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [130]:
np.arange(1,3)

array([1, 2])

In [132]:
np.arange(1,10).reshape(3,3) + 7

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [136]:
np.arange(1,19).reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [134]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [137]:
np.arange(1,19).reshape(3,6) + np.arange(1,7).reshape(3,2)

ValueError: operands could not be broadcast together with shapes (3,6) (3,2) 

In [139]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [140]:
x.sum()

325

In [141]:
# sum items by column
x.sum(axis=0)

array([55, 60, 65, 70, 75])

In [142]:
#sum items by rows
x.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [144]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [145]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [157]:
#use .seed() to freeze the random state of your values
np.random.seed(5)
y = np.random.randint(1,10,5)
y

array([4, 7, 7, 1, 9])

In [159]:
# comparison operator in numpy
x > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [160]:
# Pandas - python library for data analysis

# series and dataframe
# series - single column
# dataframe - multiple columns

In [161]:
sample = np.arange(1,11)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
import pandas as pd

In [164]:
sample = pd.Series(sample)
sample

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [165]:
sample[8]

9

In [168]:
df = np.random.randint(100,500,12).reshape(4,3)
df

array([[485, 310, 203],
       [244, 105, 414],
       [356, 488, 210],
       [264, 461, 279]])

In [174]:
df = pd.DataFrame(data=df, columns=["Jan","Feb", "Mar"], index=["MTN","UBA", "CNN", "Jumia"])
df

Jan  Feb  Mar
MTN    485  310  203
UBA    244  105  414
CNN    356  488  210
Jumia  264  461  279

In [175]:
df.to_csv("demo.csv")

In [181]:
#importing data in pandas

df = pd.read_html("https://en.wikipedia.org/wiki/The_World%27s_Billionaires")
df[2]

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [182]:
# Exploratory data analysis (EDA)
# check rows and columns
df[2].shape

(10, 6)

In [183]:
df = df[2]

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   No.                          10 non-null     int64 
 1   Name                         10 non-null     object
 2   Net worth (USD)              10 non-null     object
 3   Age                          10 non-null     int64 
 4   Nationality                  10 non-null     object
 5   Primary source(s) of wealth  10 non-null     object
dtypes: int64(2), object(4)
memory usage: 608.0+ bytes


In [186]:
df.describe()

No.        Age
count  10.00000  10.000000
mean    5.50000  71.700000
std     3.02765  12.247902
min     1.00000  51.000000
25%     3.25000  65.500000
50%     5.50000  70.500000
75%     7.75000  80.250000
max    10.00000  92.000000

In [187]:
#accessing single column
df["Name"]

0    Bernard Arnault & family
1                   Elon Musk
2                  Jeff Bezos
3               Larry Ellison
4              Warren Buffett
5                  Bill Gates
6           Michael Bloomberg
7        Carlos Slim & family
8               Mukesh Ambani
9               Steve Ballmer
Name: Name, dtype: object

In [191]:
#Accessing multiple columns
df[["Name","Age", "Net worth (USD)"]]

Name  Age Net worth (USD)
0  Bernard Arnault & family   74    $211 billion
1                 Elon Musk   51    $180 billion
2                Jeff Bezos   59    $114 billion
3             Larry Ellison   78    $107 billion
4            Warren Buffett   92    $106 billion
5                Bill Gates   67    $104 billion
6         Michael Bloomberg   81   $94.5 billion
7      Carlos Slim & family   83     $93 billion
8             Mukesh Ambani   65   $83.4 billion
9             Steve Ballmer   67   $80.7 billion

In [194]:
# removing a column
df.drop("Age", axis=1)

No.                      Name Net worth (USD)    Nationality  \
0    1  Bernard Arnault & family    $211 billion         France   
1    2                 Elon Musk    $180 billion  United States   
2    3                Jeff Bezos    $114 billion  United States   
3    4             Larry Ellison    $107 billion  United States   
4    5            Warren Buffett    $106 billion  United States   
5    6                Bill Gates    $104 billion  United States   
6    7         Michael Bloomberg   $94.5 billion  United States   
7    8      Carlos Slim & family     $93 billion         Mexico   
8    9             Mukesh Ambani   $83.4 billion          India   
9   10             Steve Ballmer   $80.7 billion  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [197]:
# removing multiple column
df.drop(["Age","Nationality"], axis=1)

No.                      Name Net worth (USD)  \
0    1  Bernard Arnault & family    $211 billion   
1    2                 Elon Musk    $180 billion   
2    3                Jeff Bezos    $114 billion   
3    4             Larry Ellison    $107 billion   
4    5            Warren Buffett    $106 billion   
5    6                Bill Gates    $104 billion   
6    7         Michael Bloomberg   $94.5 billion   
7    8      Carlos Slim & family     $93 billion   
8    9             Mukesh Ambani   $83.4 billion   
9   10             Steve Ballmer   $80.7 billion   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [202]:
# adding new column
df["Double Age"] = df["Age"] * 2
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [198]:
emp = {
    "name":"wale"
}

In [199]:
emp

{'name': 'wale'}

In [200]:
emp["age"] =  18

In [201]:
emp

{'name': 'wale', 'age': 18}

In [203]:
#renaming columns



No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [205]:
df.columns

Index(['No.', 'Name', 'Net worth (USD)', 'Age', 'Nationality',
       'Primary source(s) of wealth', 'Double Age'],
      dtype='object')

In [208]:
#renaming columns
df = df.rename(columns={"No.":"S/N"})
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [216]:
# accessing rows
df.loc[1:5]

S/N            Name Net worth (USD)  Age    Nationality  \
1    2       Elon Musk    $180 billion   51  United States   
2    3      Jeff Bezos    $114 billion   59  United States   
3    4   Larry Ellison    $107 billion   78  United States   
4    5  Warren Buffett    $106 billion   92  United States   
5    6      Bill Gates    $104 billion   67  United States   

  Primary source(s) of wealth  Double Age  
1               Tesla, SpaceX         102  
2                      Amazon         118  
3          Oracle Corporation         156  
4          Berkshire Hathaway         184  
5                   Microsoft         134

In [217]:
# dropping a row
df.drop(1,axis=0)

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [219]:
# insert a row/multiple rows
df.append(df, ignore_index=True)

S/N                      Name Net worth (USD)  Age    Nationality  \
0     1  Bernard Arnault & family    $211 billion   74         France   
1     2                 Elon Musk    $180 billion   51  United States   
2     3                Jeff Bezos    $114 billion   59  United States   
3     4             Larry Ellison    $107 billion   78  United States   
4     5            Warren Buffett    $106 billion   92  United States   
5     6                Bill Gates    $104 billion   67  United States   
6     7         Michael Bloomberg   $94.5 billion   81  United States   
7     8      Carlos Slim & family     $93 billion   83         Mexico   
8     9             Mukesh Ambani   $83.4 billion   65          India   
9    10             Steve Ballmer   $80.7 billion   67  United States   
10    1  Bernard Arnault & family    $211 billion   74         France   
11    2                 Elon Musk    $180 billion   51  United States   
12    3                Jeff Bezos    $114 billion   59  United States   
13    4             Larry Ellison    $107 billion   78  United States   
14    5            Warren Buffett    $106 billion   92  United States   
15    6                Bill Gates    $104 billion   67  United States   
16    7         Michael Bloomberg   $94.5 billion   81  United States   
17    8      Carlos Slim & family     $93 billion   83         Mexico   
18    9             Mukesh Ambani   $83.4 billion   65          India   
19   10             Steve Ballmer   $80.7 billion   67  United States   

           Primary source(s) of wealth  Double Age  
0                                 LVMH         148  
1                        Tesla, SpaceX         102  
2                               Amazon         118  
3                   Oracle Corporation         156  
4                   Berkshire Hathaway         184  
5                            Microsoft         134  
6                       Bloomberg L.P.         162  
7   Telmex, América Móvil, Grupo Carso         166  
8                  Reliance Industries         130  
9                            Microsoft         134  
10                                LVMH         148  
11                       Tesla, SpaceX         102  
12                              Amazon         118  
13                  Oracle Corporation         156  
14                  Berkshire Hathaway         184  
15                           Microsoft         134  
16                      Bloomberg L.P.         162  
17  Telmex, América Móvil, Grupo Carso         166  
18                 Reliance Industries         130  
19                           Microsoft         134

In [223]:
# sorting data
df.sort_values(by="Name", ascending=False)

S/N                      Name Net worth (USD)  Age    Nationality  \
4    5            Warren Buffett    $106 billion   92  United States   
9   10             Steve Ballmer   $80.7 billion   67  United States   
8    9             Mukesh Ambani   $83.4 billion   65          India   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
3    4             Larry Ellison    $107 billion   78  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
1    2                 Elon Musk    $180 billion   51  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
5    6                Bill Gates    $104 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   

          Primary source(s) of wealth  Double Age  
4                  Berkshire Hathaway         184  
9                           Microsoft         134  
8                 Reliance Industries         130  
6                      Bloomberg L.P.         162  
3                  Oracle Corporation         156  
2                              Amazon         118  
1                       Tesla, SpaceX         102  
7  Telmex, América Móvil, Grupo Carso         166  
5                           Microsoft         134  
0                                LVMH         148

In [232]:
# filtering data
df[(df["Nationality"] != "United States") & (df["Age"] > 60)]

S/N                      Name Net worth (USD)  Age Nationality  \
0    1  Bernard Arnault & family    $211 billion   74      France   
7    8      Carlos Slim & family     $93 billion   83      Mexico   
8    9             Mukesh Ambani   $83.4 billion   65       India   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130

In [233]:
df[(df["Nationality"] != "United States") | (df["Age"] > 60)]

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [238]:
df[df["Nationality"].isin(["India", "Mexico"])]

S/N                  Name Net worth (USD)  Age Nationality  \
7    8  Carlos Slim & family     $93 billion   83      Mexico   
8    9         Mukesh Ambani   $83.4 billion   65       India   

          Primary source(s) of wealth  Double Age  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130

In [240]:
# useful functions
def firstname(x):
    return x.split()[0]

In [242]:
firstname("Elon Musk")

'Elon'

In [243]:
df["firstname"] = df["Name"].apply(firstname)
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname  
0                                LVMH         148   Bernard  
1                       Tesla, SpaceX         102      Elon  
2                              Amazon         118      Jeff  
3                  Oracle Corporation         156     Larry  
4                  Berkshire Hathaway         184    Warren  
5                           Microsoft         134      Bill  
6                      Bloomberg L.P.         162   Michael  
7  Telmex, América Móvil, Grupo Carso         166    Carlos  
8                 Reliance Industries         130    Mukesh  
9                           Microsoft         134     Steve

In [244]:
def lastname(x):
    return x.split()[1]

In [246]:
lastname("Elon Musk")

'Musk'

In [247]:
df["Lastname"] = df["Name"].apply(lastname)
df

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname   Lastname  
0                                LVMH         148   Bernard    Arnault  
1                       Tesla, SpaceX         102      Elon       Musk  
2                              Amazon         118      Jeff      Bezos  
3                  Oracle Corporation         156     Larry    Ellison  
4                  Berkshire Hathaway         184    Warren    Buffett  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [248]:
#first 5 rows
df.head()

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   

  Primary source(s) of wealth  Double Age firstname Lastname  
0                        LVMH         148   Bernard  Arnault  
1               Tesla, SpaceX         102      Elon     Musk  
2                      Amazon         118      Jeff    Bezos  
3          Oracle Corporation         156     Larry  Ellison  
4          Berkshire Hathaway         184    Warren  Buffett

In [249]:
#last 5 rows
df.tail()

S/N                  Name Net worth (USD)  Age    Nationality  \
5    6            Bill Gates    $104 billion   67  United States   
6    7     Michael Bloomberg   $94.5 billion   81  United States   
7    8  Carlos Slim & family     $93 billion   83         Mexico   
8    9         Mukesh Ambani   $83.4 billion   65          India   
9   10         Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age firstname   Lastname  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [252]:
df.value_counts("Nationality")

Nationality
United States    7
France           1
India            1
Mexico           1
dtype: int64

In [253]:
df["Nationality"].unique()

array(['France', 'United States', 'Mexico', 'India'], dtype=object)

In [254]:
df["Nationality"].nunique()

4

In [255]:
# top 3 billionaire
df.head(3)

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   

  Primary source(s) of wealth  Double Age firstname Lastname  
0                        LVMH         148   Bernard  Arnault  
1               Tesla, SpaceX         102      Elon     Musk  
2                      Amazon         118      Jeff    Bezos

In [259]:
df["Age"].sort_values(ascending=False).head(3)

4    92
7    83
6    81
Name: Age, dtype: int64

In [263]:
df.sort_values(by="Age", ascending=False).head(3)

S/N                  Name Net worth (USD)  Age    Nationality  \
4    5        Warren Buffett    $106 billion   92  United States   
7    8  Carlos Slim & family     $93 billion   83         Mexico   
6    7     Michael Bloomberg   $94.5 billion   81  United States   

          Primary source(s) of wealth  Double Age firstname   Lastname  
4                  Berkshire Hathaway         184    Warren    Buffett  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
6                      Bloomberg L.P.         162   Michael  Bloomberg

In [267]:
df["Nationality"] = df["Nationality"].replace(to_replace="United States",value="USA")
df

S/N                      Name Net worth (USD)  Age Nationality  \
0    1  Bernard Arnault & family    $211 billion   74      France   
1    2                 Elon Musk    $180 billion   51         USA   
2    3                Jeff Bezos    $114 billion   59         USA   
3    4             Larry Ellison    $107 billion   78         USA   
4    5            Warren Buffett    $106 billion   92         USA   
5    6                Bill Gates    $104 billion   67         USA   
6    7         Michael Bloomberg   $94.5 billion   81         USA   
7    8      Carlos Slim & family     $93 billion   83      Mexico   
8    9             Mukesh Ambani   $83.4 billion   65       India   
9   10             Steve Ballmer   $80.7 billion   67         USA   

          Primary source(s) of wealth  Double Age firstname   Lastname  
0                                LVMH         148   Bernard    Arnault  
1                       Tesla, SpaceX         102      Elon       Musk  
2                              Amazon         118      Jeff      Bezos  
3                  Oracle Corporation         156     Larry    Ellison  
4                  Berkshire Hathaway         184    Warren    Buffett  
5                           Microsoft         134      Bill      Gates  
6                      Bloomberg L.P.         162   Michael  Bloomberg  
7  Telmex, América Móvil, Grupo Carso         166    Carlos       Slim  
8                 Reliance Industries         130    Mukesh     Ambani  
9                           Microsoft         134     Steve    Ballmer

In [268]:
df.sort_values(by="Age", ascending=False)["Name"].head(3)

4          Warren Buffett
7    Carlos Slim & family
6       Michael Bloomberg
Name: Name, dtype: object

In [ ]:
# handling missing data